### ISSUE TITLE
Show errors to the user

### ISSUE THREAD

**Issue by fatso83** [hut8/github-contributions#17]
Since I was already warned that the site was slow, I didn't mind that I was still waiting for results after a minute. But as the site was still showing its cubic spinner after ten minutes, I looked in the Dev Tools that showed a 500 Error ... 

So the query probably failed quite early, but I was not warned. Handle the error and tell the user you are overloaded (or whatever).

**Comment by hut8** [comment]
This was on my todo list. I'll get this done today; I just didn't know anyone was using this :)

**Comment by hut8** [comment]
By "today" I meant "in 95 days"
